services:
  - type: web
    name: qr-attendance-system
    env: node
    plan: free
    buildCommand: npm install && npm run init-db
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: ./attendance.db
      - key: QR_TOKEN_EXPIRY_SECONDS
        value: 30
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100